# Generated by Django 4.0.3 on 2022-06-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(default='', max_length=25)),
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
